Spotifyd/spotifyd

- spotifyd.service
Added a systemd service file to enable running systemd as a service on a system running systemd.
> Added systemd service file.

- src/socket.c
Hi.  I often just want to listen to a single album, but found it difficult since spotifyd is very track-centric.  Adding album names allows me to easily grep on that to find what I want.
> Added album name to track printouts

- scripts/spotifyd-nowplaying
EDIT: Yeah, I'm as dumb as a rock. I see you fixed the nowplaying script already. Anyhow, I added an extra line to deal with the case where spotifyd isn't running.
> Updated spotifyd-nowplaying to notify if spotifyd isn't running.

- Cargo.lock
- src/config.rs
- src/main.rs
Had no experience whatsoever with Rust, so just hardcoded "Spotifyd" as device name to make compatible with new librespot version.
> Temp fix using updated librespot.

- Cargo.lock
This updates the dependencies newer versions and also closes #74.
> Updated Cargo.lock

- Cargo.lock
- src/config.rs
- src/main_loop.rs
- src/setup.rs
Changeset 817dff06bfd3bcaca00642ffdd8be72bb6c22e9a of librespot
introduces new members to `SessionConfig` and `ConnectConfig`.
This commit fixes the compilation issue.
disclaimer: I'm not fluent in Rust and did my best to make this work :)
> libresport interface change compilation fixes

- Cargo.lock
- src/main.rs
- src/main_loop.rs
- src/setup.rs
Fixes the compilation error as described in: https://github.com/Spotifyd/spotifyd/issues/133
As I mentioned in the ticket, I don't know the code so I'm not sure this code change doesn't have any undesired consequences.
> Fix "expected u16, found i32" compilation error

- Cargo.lock
Resolves #205 
I am unsure if I have gone about this the wrong way; haven't worked with Rust before.
> Bump librespot version.

- src/config.rs
Fixes #170 
As #170 describes, the `--backend` argument does not seem to do anything at the moment. When there is no configuration file available, the backend cannot be specified and it is falling back to its default (`alsa`).
This PR will make use of the `--backend` command line argument whenever the config option (in the configuration file) is not supplied.
Ideally I would say that the command line argument should always take preference over the configuration file, but currently username and password also seem to prioritize the configuration file above their command-line argument. That's outside the scope of this PR.
> Use --backend as fallback for backend in configuration file

- README.md
> Added section about cache_path

- .travis.yml
i accidentialy left the deploy section commented out. now it should make releases again.
> Uncomment deploy section

- src/config.rs
> fix username and password_cmd logging

- .github/workflows/cd.yml
This should fix the problem of the tars having the release/target subfolders
> fix tar package having subfolders

- src/main.rs
Prior to this commit, logging started after reading the configuration file. This prevented logging statements within that method to correctly show up in the logs. The commit moves the initialization right after the CLI arguments have been passed, allowing all logging statements to function properly.
> refactor logging initialization

- .gitignore
- Cargo.lock
- src/dbus_mpris.rs
Closes #161.
Fixes #258, although a `rspotify` merge is preferred.
__Note from SirWindfield:__ I had to edit your original comment as Github only checks for closing keywords on the first comment 😄
> refactor mpris implementation as specified in issue #322

- Cargo.lock
- Cargo.toml
Just making sure that the lockfile has been generated correctly and CI passes :)
> bump version to v0.2.18

- .github/workflows/ci.yml
- .travis.yml
> Run CI only on changes affecting *.rs files

- README.md
> docs(readme): refactor readme file

- README.md
Currently it is giving 404, i think it was typo
> Update pre-built binaries link

- src/config.rs
> Remove conflicting proxy short flag

- README.md
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Compile on openSUSE

- src/dbus_mpris.rs
Hi, first of all, I am a newbie of Rust, so if the code is not good enough please guide me 🙇 
this PR is trying to fix this issue
https://github.com/Spotifyd/spotifyd/issues/417
please review, thanks!
> fix 417 OpenUri does not work

- src/config.rs
> fix zeroconf_port config entry

- Cargo.toml
So that there is a link from docs.rs to github
> add repository url to Cargo.toml

- README.md
- src/setup.rs
This merge request adds a badge from shields.io which displays the number of spotifyd downloads from crates.io
See #488
> Add crates.io badge to readme

- README.md
> Crates.io download count badge now links to spotifyd's crates.io page when you click it

- src/config.rs
- src/utils.rs
> Fix CI lint errors

- .github/ISSUE_TEMPLATE/bug-report.md
this is much more readable in bug reports
> add backticks to the bug report

- .github/workflows/cd.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> bump v0.3.2

- docs/src/installation/Ubuntu.md
See #1123 for discussion.
Fixes #1123.
> docs: use rustup for ubuntu installation

- src/alsa_mixer.rs
- src/config.rs
> Hopefully get CI passing

- src/dbus_mpris.rs
Since we now have our own domain, we should use that before committing to the one from GitHub before the release.
(The shorter name completely changed the formatting somehow.)
> switch to project domain for controls interface

- src/dbus_mpris.rs
New method to allow to set shuffle value, copy of #1173
> Shuffle setter.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Last preparations before the next release. :)
Fixes #1189.
If you think that everything's fine, I can also bump the version number.
> preparations for 0.3.5

- docs/src/config/File.md
- docs/src/config/services/Systemd.md
> fix docs formatting and mention system-wide MPRIS

- CHANGELOG.md
- Cargo.toml
> build: revert default features to alsa_backend

- docs/src/installation/source.md
@fallingcats Does this addition look good? Are there additional things that should be added?
> docs: mention potentially needed libclang-dev dependency

- .github/workflows/cd.yml
> cd: use ubuntu-20.04 to build linux images

- README.md
Premium requirement is already stated right above as a note, and [space](https://www.youtube.com/watch?v=bZUpggRKOms)s are quite allowed:
```shell
spotifyd --device-name "✨ 🛰️ 🌌 🛸 🪐"
```
> Remove outdated # Common Issues from README
