- README.md
- src/queue.c
The floating point exception people were running into is caused by the queue being empty and then trying next/prev which uses the modulus operator on `queue_len`, which is 0 if it is empty, resulting in division by zero.
The problem with spotifyd 'grabbing' audio turned out not to be a problem with spotifyd. See the commit message for details.
> Fixes #2 & #8.

- src/alsa-audio.c
- src/audio.c
- src/audio.h
This small fix closes the alsa device if no audio data to play is available.
It automatically gets reopened when there is something to play.
I tried to make as less changes as possible and these changes seemed to be the
easiest way to achieve this. If you got any other idea please let me know!
> Close alsa if no song is playing, fixes #16

- README.md
- contrib/spotifyd.service
This should be used for downstream packagers in general, but should also help those manually installing easily set this up to run automatically on systemd-based distributions.
Of course, this won't affect other distributions, nor will it limit current functionality in any way.
Let me know if any bit need clarification.
> Include a reference systemd.service file

- README.md
I noticed some grammar and spelling errors in the README.md file and corrected them accordingly. I also made some changes for clarity.
Also, I would like to bring to attention the line:
> Values can be surrounded by double quotes (") which is useful if it contains the comment character (#).
was changed to
>Values can be surrounded by double quotes (") which is useful if **the value** contains the comment character (#).
for clarity. Please correct this is my assumption for what the "it" stood for was incorrect.
> Edited README.md for correctness and clarity

- README.md
This fixes a few typos in the README and capitalizes ALSA and PulseAudio where appropriate.
> Improve grammar and fix a typo in the README

- README.md
Add sentence with link to the wiki for more detailed install instructions.
I also created 2 wiki pages with install instructions for Ubuntu and Raspberry Pi.
> Add wiki link for detailed install instructions

- src/dbus_mpris.rs
According to dbus specification it should be PlaybackStatus and not
PlayBackStatus.
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html
> Fix dbus property

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/setup.rs
fixes #129 
I have no doubt there is a cleaner way to separate out all of the alsa logic without the need for conditional compilation. However I don't know any rust (yet) so this was just an attempt to prove that spotifyd will actually compile and run on OSX. If you have any tips on a cleaner way to implement this I would love some pointers in the right direction.
> Make the alsa backend optional and add support for the portaudio backend to enable OSX support

- Cargo.lock
- src/config.rs
Running `cargo update` seems to have included `librespot`, which has added another key value pair to core.config.SessionConfig.
I've built and run this successfully on Ubuntu Cosmic (18.10).
> Updated Cargo.lock version and added ap_port field required by librespot.core.config.SessionConfig

- src/config.rs
Some networks block Spotify Connect, probably using some simple packet inspection. Switching to port 443 fixes this, at least for me.
> Use port 443 instead of 80

- contrib/spotifyd.service
Spotifyd crashes if it starts before either the sound card is configured or the network is available. Whilst this is not too bad, it causes a restart of the service when started at boot. It is nicer to just depend on the targets that systemd provides to signal availability of both.
> Add dependencies to the spotifyd systemd service

- snap/snapcraft.yaml
As discussed over mail, this is a pull request to add support for building snaps.
A single snap (built for many architectures) in the Snap Store will be installable on numerous popular Linux distributions with no changes. It’ll also be discoverable via the [Snap Store](https://snapcraft.io/store), where releases are under your control.
If you're willing to publish this under the spotifyd project name, you just need to [create an account](https://snapcraft.io/snaps) and then [register the spotifyd name](https://snapcraft.io/register-snap).
A snap file created by snapcraft (our free software tool for building snaps) can then be released in the Snap Store with `snap push --release stable *.snap`. You'll want to install snapcraft (brew install snapcraft, snap install snapcraft, or apt install …
> Create snapcraft.yaml to enable building of snaps

- snap/snapcraft.yaml
This makes it easier to build stable releases.
This relies on you keeping a stable release in the beta channel in the store. Clearly you can also have the same stable release in the stable channel.
On every build the `override-pull` section will query the store to see what version is in the beta channel. If it's older the the current tagged release in github, we checkout the latest release, build that.
So, to prepare, leave the beta channel empty. Merge this branch and the next build will see the beta channel is empty, and choose to build the most recent tagged release. 
Once built, you can release that to the beta channel (and once tested) release also to the stable channel.
From this point onwards any changes in master will trigger a built of the tip as there isn't a newer tagged …
> Update to add logic to build stable releases

- src/setup.rs
The device_name command parameter was not being passed
to the main loop.
> Fix --device_name argument parsing

- src/dbus_mpris.rs
This adds the `xesam:artist` metadata field from the first artist, which is usually the only one.
> Add single artist to mpris metadata

- Cargo.lock
- Cargo.toml
- src/alsa_mixer.rs
- src/config.rs
- src/dbus_mpris.rs
- src/main.rs
- src/main_loop.rs
- src/player_event_handler.rs
- src/setup.rs
This PR moves partial source code to the 2018 edition of Rust.
API wise, this won't change much. The 2018 edition improved the way how Rust code gets imported. Instead of having to write a huge chunk of `extern crate ...` statements, the code gets now pulled in as soon as someone declares its usage via `use ...`. The change introduced a new keyword too, `crate`, that is used to refer to the crate's own modules.
To make use of the 2018edition I had to upgrade the `syslog` and `log` crates. Those changed their API from `LogLevelFilter` to `LevelFilter` and I changed those two lines accordingly. 
Besides that, the 2018 edition introduced a new operator, the `?`. This one basically is the old `try!` macro you used in some part of the code. The team behind Rust decided to give it its own …
> Move to 2018 edition

- README.md
Previously, the command would fail with error code 2 and display the following
usage description:
```
usage: secret-tool store --label='label' attribute value ...
secret-tool lookup attribute value ...
secret-tool clear attribute value ...
secret-tool search [--all] [--unlock] attribute value ...
```
> Add missing `store` keyword in secret-tool command example

- README.md
Previously, there was no clear indication that a username must be explicitly
provided to Spotifyd rather than looked up in the keyring.
> Clarify usage of the use-keyring config option

- Cargo.lock
- Cargo.toml
- src/config.rs
You don't need the whole rust-crypto for just SHA-1. Also see librespot-org/librespot#239.
> Replace rust-crypto with sha-1 crate

- Cargo.lock
- src/alsa_mixer.rs
- src/setup.rs
The following commit introduces an extra parameter for the open method in both AlsaMixer and SoftMixer: https://github.com/librespot-org/librespot/commit/0e1147077c590d26d04cb469c386f0a00f69c2f3#diff-303f227033559b727a9a49c823798e48. This pull request fixes compiler error introduced by this commit.
> Fix missing parameter compiler error for Mixer open method

- src/dbus_mpris.rs
The mpris specification dictates that SupportedUriSchemes should be an array of strings.
This fixes #240.
---
Type is correct in D-Feet after the changes made in this branch.
> mpris: SupportedUriSchemes has `as` type in spec

- src/dbus_mpris.rs
Align Spotifyd's metadata fields with specification guidelines and
Spotify's metadata fields, for compatibility with existing scripts that
make use of mpris metadata.
Unified formatting for setting the metadata fields.
> Update mpris metadata

- README.md
- src/cli.rs
- src/config.rs
- src/setup.rs
See #87.
I'm very happy to change option name, description, etc. and be corrected on my rusty rust. I just found this useful and wanted to share.
> Separate config option for control (i.e. mixer) device

- .travis.yml
I reenabled clippy and rustfmt. i had no success in enabling pulseaudio for both architectures. so i left it only for x86.
> Enable clippy, rustfmt and pulseaudio for x86

- README.md
Define `the cache path' and remove ambiguity, 
Remove the repetitive 'is set to A so A is used'.
`have to exist' is not english. The bracketed text can also be removed because an explanation that the path must exist follows soon after.
First explain missing path and then shell expansion.
Remove redundant 'this means that ...'.
As a followup, what would happen if a relative path is provided? Is it allowed or must the path be absolute?
> Improve english on cache_path explanation

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/utils.rs
This commit moves away from the custom gethostname function and uses a well tested crate instead.
Closes #287.
> refactor to use gethostname crate

- Cargo.lock
- Cargo.toml
- src/utils.rs
This PR moves away from the self implemented `get_username` method and uses a crate instead.
Closes #293.
> refactor to use whoami crate

- src/config.rs
This commit makes softvol the default volume_controller if none is specified.
Fixes #294.
> fix volume_controller not having a default value

- src/config.rs
This commit adds code that manually removes any comments within the INI file before processing the config key and value pairs.
It's honestly not the prettiest solution but it's the only one I came up with.
Fixes #300.
> fix config file inline comments not being recognized

- .github/workflows/cd.yml
- .github/workflows/ci.yml
This commit adds a CI workflow to the project. It checks for the correct code style (using cargo fmt) and lints the whole project as well (using cargo clippy). The last step checks if the binary can be compiled on our target OS (using cargo check).
The commit also adds a workflow for CD. After each release, the workflow will build binaries for both Linux and macOS in two flavours: slim and full. Slim does contain nothing but the proper audio backend. Full contains all features that work correctly on the specific platform. For Linux that is dbus_keyring and dbus_mpris. For macOS it is only dbus_keyring. The resulting binaries are compressed into a .tar.gz archive and uploaded as assets to the appropiate release. The script does also create sha512 checksums and uploads them as well.
Closes …
> add CI and CD workflows

- src/dbus_mpris.rs
This commit fixes the prev and next commands not working properly over dbus. Instead of using the spotify web api, the code now uses the spotify connect connection provided by librespot.
> fix mpris prev and next command

- Cargo.lock
- Cargo.toml
- src/dbus_mpris.rs
This commit encodes the device_name before sending it over as a query value to the spotify web api. Device names containing special characters should not crash the daemon anymore.
Closes #171. Although the problem mentioned there has also been fixed by https://github.com/Spotifyd/spotifyd/commit/1197e004efc1ccb57abc208ced79a313f2293c66.
> fix device_name escaping

- README.md
The current link redirects to https://developer.spotify.com/documentation/web-api/reference/, which is a reference for the entire web api.
> Update Spotify Connect Link

- src/config.rs
This commit fixes a bug where running multiple daemons on the same account wouldn\'t work as each of them is externally seen as the same device by spotify's connect api. The reason was that the deviceid was static within the code instead of using the device_name property.
Fixes #332.
> fix spotify connect deviceid

- src/config.rs
An attempt at resolving #297 
This first commit seems to filter the backends okay, but I'm having a bit of trouble figuring out the best way to conditionally show the `use-keyring`. I can't think of a way to conditionally toggle a field since it's specified with the structopt attribute. I'm still relatively new to rust, so if anyone could point me in the right direction, that'd be great!
> feature aware cli flags

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .travis.yml
Prior to this commit, the CI builds didn't use the Cargo.lock file to build binaries. This commit will make CI builds fail if the lockfile didn't get updated after a version bump.
Closes #320.
> make ci use cargo lockfile

- src/config.rs
Prior to this commit the pid flag expected an integer as input. This is wrong behaviour. The right data type should be a string pointing to a valid file path.
Closes #340.
> fix pid cli flag expecting wrong type

- src/dbus_mpris.rs
The bug is exactly as mentioned by @SirWindfield [on the issue](https://github.com/Spotifyd/spotifyd/issues/353#issuecomment-538642273). Fix is to compare against the URL-encoded device name.
Fixes https://github.com/Spotifyd/spotifyd/issues/353.
> fix dbus-mpris device name comparison

- src/config.rs
Added option to use credential-only caching as described in issue #351 
By default this uses credential-only caching which might be not the best approach, as the default value was hardcoded with "true".
Let me know if you want to change this.
Disclaimer: I'm pretty new to all of this, so just tell me if I did something stupid. 
Edit: Fix #351
> Added option to use credential-only caching as described in #351

- README.md
This does, however, not display correctly. I think it is because none of the workflows actually passed 🙈
> add GitHub Actions badges to readme

- src/config.rs
- src/utils.rs
I'm not sure, why the device name can't contain whitespaces. However, I would just replace/ignore device names entered with whitespaces with the default, and warn the user. Which is what this does. Consider this PR highly opinionated and optional :D 
Closes #378.
> replace device name with default if contains whitespace

- .github/ISSUE_TEMPLATE/bug-report.md
This PR adds an issue template to the repo. The template mentions information that can be used to reproduce the bug and actively mentions the logs that should always be attached to issues.
> chore(templates): add issue template

- src/config.rs
The latest version of clippy includes the [option_and_then_some](https://rust-lang.github.io/rust-clippy/master/index.html#option_and_then_some) check which is causing recent builds to fail.
Example failing build: https://github.com/Spotifyd/spotifyd/pull/437/checks?check_run_id=319826888#step:6:566
> fix option_and_then_some lint error

- src/alsa_mixer.rs
If a user's volume control is not correctly configured the following (unhelpful) warning is logged:
> Couldn't set volume: "Couldn\'t find selem."
It does not say _which_ selem cannot be found. Let's output this information to help users debug their configuration files.
In my case this PR helped me discover that it was using `PCM` as the name of the selem instead of `alsa`. This led me to #283 which solved my problem.
> refactor: report name of selem that cannot be found

- src/config.rs
- src/dbus_mpris.rs
Position should be returned in microseconds.
See https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Position
> fix(mpris): position property now returns value in microseconds

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
Librespot supports using HTTP proxies to connect to spotify servers. This PR adds a config directive for that. 
This might also help some people who experience an error like in #175  . Helped me at least.
Fixes #143.
> Add proxy support

- .travis.yml
Travis doesn't support filtering for file paths or types of commit.
> revert path filter for builds

- .github/workflows/cd.yml
This project uses GitHub Actions to create builds, which is great. However, the workflow for this uses a build matrix that builds every `artifact_type` (slim, full) for every `build_target` (macos, macos-rodio, ubuntu) for every `feature` ('', 'dbus_keyring,dbus_mpris).
So the `cd.yml` creates twice as many workers than necessary, while occasionally overwriting the "slim" version with a "slim" version that has all features enabled (and the other way round), see #464.
This PR improves three things:
* Rename the "ubuntu" target to "linux", so it better represents what it does
* Set the name of the job to "macos-slim", "macos-full", "linux-slim", etc. to give a better overview which jobs are running
* Move the feature definition into the `include` node, this solves a multiplication of …
> Improve CD workflow matrix (fixes #464)

- src/config.rs
structopt automatically uses doc comments to create help messages. Moving these comments to normal comments makes them disappear from the `--help` message
> fix help message

- .github/workflows/cd.yml
This PR adds a workflow that creates "arm-unknown-linux-gnueabihf" builds for the "slim" and "full" versions with "alsa_backend" using cross compilation.
The resulting packages are called `spotifyd-linux-armhf-slim.tar.gz` and `spotifyd-linux-armhf-full.tar.gz`.
As a new package source has to be installed, `ubuntu-latest` cannot be used here, so the new step uses `ubuntu-18.04` (which currently is the same, but we need to be sure).
Instead of a full `sbuild` setup, the armhf packages are installed and copied manually, which may look dirty. Unfortunately, `dbus-rs` needs quite some system packages, so we need to download and put them where the linker expects them to be. This process is described here: https://github.com/diwic/dbus-rs/issues/184#issuecomment-520228758
Issues:
- I'm not sure …
> add CD support for armv6 and armv7

- README.md
I have created docs to help new users run as a daemon on macOS (which is the whole point of spotifyd!
It's a little tricky, so tried to call out gotchas.
> add documentation for running on macOS

- Cargo.toml
- src/utils.rs
Cleans up the shell discovery code a little bit by relying on system function calls instead of parsing the `/etc/passwd` file on linux devices.
> Cleanup code

- README.md
- src/config.rs
- src/main_loop.rs
- src/setup.rs
See Issue #450. 
Sorry for all the git noise. I am unfit for git. For rust as well.
> feat: add support for device-type

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main_loop.rs
- src/setup.rs
I haven't done thorough testing yet, but 0.1.1 includes https://github.com/librespot-org/librespot/pull/427 which claims to gracefully handle disconnect issues.
0.1.1 also includes a new `ConnectConfig` variable called autoplay, which I took the liberty of bubbling up to spotifyd configs.
Let's use this for PR for testing to see if it fixes #156 #458 #175
> Bump librespot to 0.1.1, hopefully fixing disconnect issues

- CONTRIBUTING.md
- hooks/pre-commit
- setup-dev-workspace.sh
The pre-commit hook ensures multiple things before commiting code:
1) All Rust code is properly formatted
2) All linting errors are fixed
3) All tests are passing
4) The project can be compiled inside of the local development env
> chore(git): add git pre-commit and setup script

- README.md
This appears to work, should pop up a keychain auth request on first run.
> chore(readme): macOS keychain CLI documentation

- src/dbus_mpris.rs
Users can now pass down their own client id to circumvent rate limit errors
fix #507
> feat: add client_id environment variable

- src/dbus_mpris.rs
This commit removes the deprecated `user-read-birthdate` scope, making the login request now succeed again.
Fixes #507.
> fix: custom client_id not working

- README.md
`README.md` mentions problems with the Spotify Connect functionality (also called discovery mode). It seems that the problems are resolved: issues are closed and I confirm that I am able to use the functionality with the current spotifyd version (0.2.24).
This PR removes the note about the past issues from the `README.md` file.
Have a nice day!
> Remove notes on closed issues in README.md

- src/config.rs
The code is copy pasted from password_cmd.
In the first commit the doubled check for an empty `password_cmd` is removed.
> feat: username_cmd config option

- Cargo.toml
- README.md
I did this for myself, because I wanted to have my Debian installation to install things using the package manager and https://github.com/mmstick/cargo-deb makes things much easier.
> biuld(deb): add support for building deb packages with cargo-deb

- README.md
> chore(readme): add `--locked` to installation instructions

- README.md
As stated in #563, `cargo install spotifyd` does not compile
successfully due to a compilation error caused by `librespot`.
In order to solve this, it was mentioned in librespot-org/librespot#477
that adding the `--locked` file solves the problem since it is
preventing some of their dependencies to change and keep fixed.
Therefore, if we use `cargo` to install `spotifyd` it is necessary
for the time being to use the `--locked` file too.
- Added `Installing with Cargo` section in README.md with this
commad specs.
Closes #563 partially, since a better solution should be found
in the future.
I wonder if it is possible (I've never seen it) to add the `--locked` flag in the `Cargo.toml` for `librespot` similar to:
```toml
librespot = { version = "0.1.1", default-features = false, features = …
```
> chore(readme): add `cargo install` to installation instructions

- .github/workflows/cd.yml
* add *-default builds
* remove macos-rodio-* builds
* slim and default linux builds use pulseaudio as audio backend
Related #589 (provides pulseaudio binaries, pipe support depends on #354)
> ci!: create full, default and slim artifacts

- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- src/config.rs
I had a problem with '#' being in my password and i saw it was an issue with serde_ini and in [this](https://github.com/Spotifyd/spotifyd/issues/402) milestone so did this. i think it works
> TOML config

- src/setup.rs
reduced unnecessary complexity from setup.rs by replacing match for boolean with matches! macro.
lint error fix for #740
> Fixed Linting issues in src/setup.rs

- src/dbus_mpris.rs
https://github.com/Spotifyd/spotifyd/issues/397
Simple PR that expose the Volume through dbus 
Tested the volume is zero when nothing is playing and initial_volume when playing
It's basically  zack6849 patch
> Add volume property

- Cargo.lock
- Cargo.toml
@SirWindfield (my?) cargo seems to change the format of the lockfile slighly, normally i would use `--locked` but that not possible when bumping versions.
I did push a 0.2.25 tag to this branch, but im not sure if that will show up in origin. Otherwise i think you are the only one with push rights to master
> bump version to 0.2.25

- Cargo.lock
- Cargo.toml
Refer to https://github.com/Spotifyd/spotifyd/pull/627#issuecomment-709347897; `failure` was not actually used, and is deprecated anyway, so this MR removes references to it in Cargo.toml and Cargo.lock.
Closes #627.
> Remove `failure' as a dependency

- README.md
Since we already have enough maintainers as for now, I think we can remove the "Looking for maintainers" note from the Readme.
> Remove "looking for maintainers"

- .github/workflows/ci.yml
This commit reverts 976a41f9c75a75d08bd6ae68048788e161ae8c64 and 0866ed9d21d8a550a1ef69aa812bb1f5be9d5b1d.
> revert: ci changes for hanging tasks

- README.md
- src/config.rs
- src/main_loop.rs
- src/setup.rs
#730 
This defines the `use_mpris` configuration setting in the main
configuration file. Set this to `false` in case you have a headless
`spotifyd` instance, running in session lacking a dbus session.
> Introduce use_mpris configuration setting

- .github/workflows/cd.yml
in reply to this comment https://github.com/Spotifyd/spotifyd/issues/719#issuecomment-760148418
tested on my [fork](https://github.com/Spotifyd/spotifyd/runs/1701099531) and says it now uses the correct version, just like the last one this PR should also be reverted when it is fixed.
After this we can make a PR to push a new version/tag with 0.3 (https://github.com/Spotifyd/spotifyd/issues/765#issuecomment-760146839)
> also pin rust version on CI

- Cargo.lock
- Cargo.toml
after this we can create a new tag with 0.3.0 and push to crates.io
> bump version to 0.3.0

- README.md
- Make library-table consistent.
- Add dependencies for people trying to compile it on Arch(based) distros, in case they don't use AUR.
I decided to remove all commas, since its easier to copy/paste and use them as arguments for the used package manager.
> Improve 'Compiling from source' section

- README.md
Adds quotes around the value of the example initial_volume option
Also adds a note warning that the type will change in 0.4
> update readme to reflect initial_volume's type being string

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main_loop.rs
- src/process.rs
- src/setup.rs
Waiting for https://github.com/librespot-org/librespot/pull/485 to be merged and a new librespot version.
Furthermore I'm unsure about the naming of strings in the `PLAYER_EVENT`, are those coming from somewhere specifically, e.g. `change`, `start`, `stop` ? 
For the gapless part alternatively using `.. Default::default()`, would have the same result, but might might make future changes non breaking (good or bad).
__Edit by SirWindfield:__
Fixes #85.
> Update librespot dependency

- docs/src/config/File.md
Several device_type examples aren't valid and cause a panic.
> Update config file to use valid device_type entries

- src/utils.rs
Fix:
```
error[E0425]: cannot find value `get_shell_ffi` in this scope                                                                                                              
--> src/utils.rs:71:48                                                                                                                                                   
|                                                                                                                                                                       
71 |     let shell = env::var("SHELL").ok().or_else(get_shell_ffi);                                                                                                        
|                                                ^^^^^^^^^^^^^ not found in this scope
```
> Fix build on FreeBSD

- docs/src/SUMMARY.md
I found the Document not found error. There was a typo error on 'installation' word. I just corrected that.
> Update Summary with correct link to MacOS docs

- src/config.rs
Closes #355
Also removed a ToDo and added a macro to remove duplicated code in the fmt::Debug implementation.
Preceded by #360
> Added debug_credentials flag

- src/main.rs
The current error message might be hard to detect as such, as you can see in  #924. This PR aims to make it easier to figure out the actual reason for panicking.
> improve panic message

- Cargo.lock
- Cargo.toml
- src/alsa_mixer.rs
- src/config.rs
- src/dbus_mpris.rs
- src/main.rs
- src/main_loop.rs
- src/process.rs
- src/setup.rs
- src/utils.rs
This is an initial attempt at upgrading librespot to 0.2.0. That also required:
- upgrading tokio to 1.0
- reworking `dbus_mpris.rs` to use `dbus-crossroads`. 
The dbus-mpris stuff was all written using an older version of `dbus-rs`, which integrated with tokio 0.1, and therefore needed to be upgraded. I initially tried to do this with the `dbus-tree` package to minimise code changes, but I found it difficult to reason about the threading model, and eventually switched to dbus-crossroads. I hope that's ok!
I've left a number of TODOs in the code:
- some are product-ish questions (e.g. "do we want to support this new librespot feature in the spotifyd config?")
- some are places where the code works on my machine, but I'm unclear on whether it will work for everyone.
I'd love some input on …
> Upgrade librespot to 0.2.0

- src/config.rs
As mentioned [here](https://github.com/Spotifyd/spotifyd/pull/1059#issuecomment-1052372090), the [`map_flatten`](https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten) clippy lint has been promoted to a warning and would cause the CI to fail. This PR just applies `cargo clippy --fix` (and `cargo fmt`).
> fix clippy `map_flatten` lint

- docs/src/config/File.md
As I was reading the documentation I found some grammatical errors and took the liberty to fix them. 
Proposing a few minor corrections of comments in the example configuration file.
> Minor comment cleanup in example config file

- docs/src/installation/FreeBSD.md
Create this page from Raspberry pi Install one
> Add instructions to install spotifyd on FreeBSD

- src/dbus_mpris.rs
- src/main_loop.rs
- src/setup.rs
> Implement PropertiesChanged event for dbus_mpris

- docs/src/installation/README.md
> update package link for Arch linux to the community repo. 

- docs/src/config/File.md
- src/config.rs
Instead of the previously advertised "autoplay on connect", `autoplay` makes the playback continue after the user's selection has ended.
I also added the option to the config file and documented it there. Apparently that was all missed, when the option was initially added (2b91a0c11d01807a3220d1177008c80a8dcc2662).
For reference, see e.g. [`librespots`'s documentation](https://github.com/librespot-org/librespot/blob/c6e97a7f8ab4b7d97b82427071b2f1555557e0cc/src/main.rs#L369-L373) for that flag.
@Spotifyd/maintainers, it would be great, if someone could review this PR!
related: #1003
> fix documentation for autoplay option

- docs/src/config/File.md
- src/config.rs
> Expose librespots support for limiting the cache size 

- Cargo.lock
- Cargo.toml
- src/dbus_mpris.rs
- src/main.rs
This mainly upgrades the `rspotify` crate to `0.11.5`. Since large parts of the API surface changed between (the previous) `0.8.0` and `0.11.5`, the changes are a bit more complex in some cases.
- no longer clones the token many times on the creation of the dbus server and instead passes an `Arc` to the API client; this facilitates requesting a new token after expiry (fixes #1074)
- avoids cloning in the `.insert_metadata()` as much as possible
- makes the `rspotify` dependency optional (only needed with `dbus_mpris`)
- fix `device_name` matching in some dbus methods, as the `device.name` is not (or no longer?) percent encoded
- `cargo update`, since otherwise `spotifyd` would not compile with the dependency updates
There is currently not much, we can do about that ugly implementation. …
> Upgrade rspotify to 0.11.5

- README.md
As the original dependabot has stopped working, the badge link is broken. So this removes it. (See #1077 )
> Removes Dependabot status badge

- docs/src/config/File.md
In order to be able to use zeroconf based authentication, it is currently necessary to omit everything related to username or password in the configuration. 
AFAICT, this is not really documented anywhere except for [this wiki entry](https://spotifyd.github.io/spotifyd/config/index.html), which does barely go into details about this. Maybe I just haven't looked in the right places for this, but several others (#938, #948) seem to have trouble finding anything as well.
> document zeroconf based authentication properly

- Cargo.lock
- Cargo.toml
- src/config.rs
Thanks to #1118, I discovered a redundant dependency (`reqwest`) that we just required for a single type that librespot uses (`reqwest::Url`), which is, however, a re-export of `url::Url`. So this should remove an unnecessary dependency. (And update `Cargo.lock`, which was necessary.)
Fixes #1118.
> replace redundant `reqwest` dependency with `url`

- src/main.rs
fixes #1107
@chinchilla-manaka, it would be great, if you'd be able to test this version on a system without `syslog-ng` installed and see if it improves the situation.
---
In addition to that, this builds upon #789 and improves the error reporting in main overall. By relying on the panic hook from `eyre` / `color_eyre` instead of using our own, we get more beautiful and clearer panic messages that are also easier to debug.
Example:
> improve error reporting

- src/dbus_mpris.rs
Added a compilation option to append device names to the end of dbus paths, this allows multiple Spotifyd daemons to be running each with a unique dbus object for MPRIS as long as they have unique device names.
> MPRIS Device Name

- src/dbus_mpris.rs
This makes some MPRIS methods more spec compliant. @wasamasa does this resolve all your issues?
I'm not sure, if the integer type casting is overly cautious the way it is currently.
Fixes #1112.
> make `Seek` and `SetPosition` functions spec compliant

- docs/src/config/File.md
- src/config.rs
- src/dbus_mpris.rs
- src/main_loop.rs
- src/setup.rs
This adds a new configuration option to configure which bus should be used by spotifyd. It addresses situations like #944 or one I personally found me in, where access to the MPRIS interface on headless systems would really help a lot.
Since I'm quite new to the codebase as well as the Rust ecosystem in general, I'm not sure if everything I changed / added was a good idea. Therefore, I'm always happy to take improvement proposals and adapt the PR accordingly. :grinning:
> add configuration option for bus type

- src/config.rs
- src/setup.rs
This is a follow-up to #1019 and reorders the credential cache logic.
Previously:
- `username` and `password` are specified: use that
- cached credentials exist: use that
- else: start discovery
Now:
- cached credentials exist for given `username`: use that
- `username` and `password` are specified: use that
- else: start discovery
Also, a cache initialization failure is properly reported to the user.
> only use cache if username matches

- .github/workflows/ci.yml
- Cargo.toml
> Specify minimum rust version

- src/dbus_mpris.rs
This patch ensures we always return the clearest possible album art URL as part of the MPRIS event sent over DBus. I noticed this after [mpris-notifier](https://github.com/l1na-forever/mpris-notifier) started showing blurry album art. Upon further inspection, the first album art item in the list returned by Spotify had become the smallest image's URL, rather than the largest.
Before:
After:
> always emit the album art URL representing the largest image to DBus

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/dbus_mpris.rs
Closes #1110
This adds a line about the minimum rust version change which landed earlier today,  replaces the title of the "Unreleased" section with 0.3.4, and bumps the version number in Cargo.toml and Cargo.lock
> Update repository for 0.3.4 release

- README.md
I'd have preferred to add the mdbook link and then put the project website link in the sidebar, but in the meantime I think this'll do.
Also, as an aside, right now https://spotifyd.rs just links to the github, docs, matrix, etc. If anyone has suggestions for changes or things to add, just let me know (the code is hosted at https://github.com/slondr/spotifyd.rs).
> Add project website link to readme

- src/dbus_mpris.rs
This is a new TransferPlayback method available for DBUS. It's useful in my setup where spotifyd is part of audio system based on dietpi micro computer. It's used to transfer playback from other active spotify device.
Also i discovered weird error when setting my spotifyd device type to S_T_B. It was returned from device() method of spotify client as STB (all capitals) and was throwing error:
```
json parse error: unknown variant `STB`, expected one of `Computer`, `Tablet`, `Smartphone`, `Speaker`, `Tv`, `Avr`, `Stb`, `AudioDongle`, `GameConsole`, `CastVideo`, `CastAudio`, `Automobile`, `Unknown` at line 16 column 18
```
I didn't find `STB` anywhere in code so i assume that spotify changes that somehow ?
> New DBUS method: TransferPlayback

- src/config.rs
- src/main.rs
- src/no_mixer.rs
- src/setup.rs
I added an alternative to "softvol" and "alsa"; "none".
If remotely changing volume, or resetting it on restart is undesired, this is a fix.
> Added alternative to disable changing volume

- Cargo.lock
- Cargo.toml
- docs/src/config/File.md
- src/setup.rs
This updates to the newest release of the keyring crate and updates the messages of the keyring query. From my testing, this is backwards compatible with the previous version – at least the parts that we were using.
Fixes #1086. (at least the last update there was, that changes in keyring, which have landed, might resolve the issue)
> update keyring crate

- .github/ISSUE_TEMPLATE/config.yml
- README.md
This removes/updates some obsolete badges and adds a new one for the matrix room. ([Preview](https://github.com/Spotifyd/spotifyd/tree/badge-updates#readme))
Justification for the individual updates / removals:
- contributors are also listed on the right side of the repo's front page and haven't been updated in a while
- cargo downloads don't accurately represent the actual downloads of this project, which probably happen more via GitHub releases or other distributions (the shown number is less than the amount of stars this repo has)
- the CI and CD badge didn't match the style of the others, so I went for the ones from shields.io
Now, when we're already at it, would you prefer a [different style](https://shields.io/#styles) for the badges?
> update badges and add link to matrix

- .github/workflows/docs.yml
This prevents the action to overwrite our custom domain name. See [here](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-add-cname-file-cname) for documentation.
> add CNAME to gh-pages

- .github/workflows/ci.yml
- Cargo.toml
- src/dbus_mpris.rs
This upgrades `rspotify` to `0.11.6` and removes the workaround that was introduced in #1079, for which there is now much better library support.
related: #1144
> remove workaround for rspotify id types

- Cargo.lock
- Cargo.toml
There were no major changes to the code. Tested to function as expected.
> Update dependencies, except librespot

- Cargo.lock
- Cargo.toml
- src/alsa_mixer.rs
- src/config.rs
- src/dbus_mpris.rs
- src/main_loop.rs
- src/no_mixer.rs
- src/process.rs
- src/setup.rs
Upgrades librespot to 0.4
- Audio normalization: I'm unsure of the changes, but I think we could improve clipping with normilazation when using softvol
- Credentials: librespot now seems to want to handle credentials storage by itself. Should we hand over this job?
> Librespot upgrade to 0.4

- docs/src/config/File.md
- src/config.rs
- src/main_loop.rs
- src/setup.rs
Add support for audio-format configuration.
Closes https://github.com/Spotifyd/spotifyd/issues/1081
> feat: option for audio format

- CHANGELOG.md
- src/main_loop.rs
I just noticed that we disabled credential caching by accident during the `librespot` upgrade.
> re-enable credential caching

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/dbus_mpris.rs
To be honest my main motivation for this is that my `cargo` isn't obeying the .toml and keep pulling rspotify 0.11.7 which breaks mpris, and now that 0.12.0 is released it feels like it makes more sense to update to that than to 0.11.7.
0.11.7 switched completely from std::time::Duration to chrono::Duration, so update our usage accordingly.
0.11.7 also added Collectionyourepisodes to the Type enum, so add it to uri_to_id.
0.12.0 added an optional Market for country code, which for now is just to None in the one spot it was required to be set.
> Update dbus_mpris to rspotify 0.12.0

- docs/src/config/File.md
Minimal docs that should point users with firewall issues in the right direction.
Based on personal discovery and the explanation in https://github.com/Spotifyd/spotifyd/issues/998#issuecomment-1807867264.
> Add brief docs describing use of fixed service port with firewall

- .github/workflows/docs.yml
As noted in the readme of [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), GitHub offers basically the same functionality by themselves. Since the old version was failing anyway, I thought that reducing dependencies might be a good idea.
(Should probably be squash-merged.)
> Use GitHub Actions for pages deployment

- docs/src/installation/README.md
> Update Arch Linux package URL in README.md

- docs/src/config/File.md
- docs/src/config/services/Systemd.md
This took me a while to figure out, so I created a PR updating the docs with something that's missing, IMO.
Systemd allows running spotifyd as a system service, or as a user service.
When running as a system service, accessing login credentials stored in a user's keyring is not possible.
When using the user's keyring to store login credentials, as described in the docs, make sure to also run the spotifyd as a user service.
> Explain that credentials from keyring can't be accessed in system service

- Cargo.lock
After 2.2.0 I submitted https://github.com/hwchen/keyring-rs/pull/156 which turned into 2.3.0 today.
OpenBSD's port currently needs patches, see PR for details.
I have only tested spotifyd's 0.3.5 release with this keyring bumped 2.3.0 instead of patching 2.0.5 and it works.
Done with `cargo update keyring`.
> Bump keyring to latest release 2.3.0 to add OpenBSD support

- docs/src/SUMMARY.md
- docs/src/config/File.md
- docs/src/installation/OpenBSD.md
- docs/src/installation/README.md
- src/utils.rs
```
error[E0425]: cannot find value `get_shell_ffi` in this scope
--> src/utils.rs:69:48
```
Otherwise spotifyd-0.3.5 works great on OpenBSD/amd64 7.4-current.
> Recognise OpenBSD to unbreak build

- Cargo.lock
On OpenBSD, ring 0.16 a) needs patches to comply with execute-only memory policies and b) does not build on sparc64, riscv64 and powerpc64.
Works for me in combination with spotify-qt on OpenBSD/amd64 7.4-current.
Done with `cargo update ureq rustls sct`.
> Update ureq, rustls and sct to bump ring>=0.17

- Cargo.lock
- Cargo.toml
- src/main.rs
Limit the attack surface of spotifyd, an internet facing network daemon with read/write filesystem access and options to execute arbitrary commands.
Most importantly, prevent fork(2)/execve(2) unless `onevent` is used.
While the set of runtime promises retains full read/write filesystem as well as network access (for now), it does exclude a number of groups of unused system calls -- the manual[0] for details.
OpenBSD's official package has been shipping this patch for a month by now without any regressions or reports of breakage.
0: https://man.openbsd.org/pledge.2
> Use pledge(2) on OpenBSD to restrict system calls

- CHANGELOG.md
- src/setup.rs
fixes #1227
This retries to enable discovery, if it fails, for several times before giving up to prevent race conditions e.g. on startup.
Before merging this, we should probably wait for feedback on the linked issue as this might be a `libmdns` issue that could be fixed instead.
> retry enabling discovery

- docs/src/SUMMARY.md
- docs/src/other/D-Bus-control.md
Adds some documentation around the MPRIS support and the additional nonstandard D-Bus interface, which doesn't seem to be available elsewhere outside of Github issues and source code.
> Add documentation for D-Bus control

- src/config.rs
Fix clippy lints by replacing `ToString` with `Display` impls.
> replace `ToString` with `Display` impls

- src/config.rs
Fixes #1277.
If you're able to test, @sad-goldfish, that would be great!
> fix default dithering behaviour

- Cargo.lock
- Cargo.toml
- docs/src/installation/Feature-flags.md
- src/config.rs
The underlying `librespot` library already supports the JACK audio backend via `rodio`. Enabling it in `spotifyd` turns out to be dead simple--just needed to add the config enum elements to pass it through!
NOTE: I have tested this on my machine running Debian testing ("trixie"). The documentation for Fedora is based on the upstream docs for librespot: https://github.com/librespot-org/librespot/blob/329a1b16074af4d1a8abe2ed017b5d4a4a070ea1/COMPILING.md#audio-library-dependencies
> Add support for `rodiojack` backend.

- Cargo.lock
Caused by https://github.com/time-rs/time/issues/681
Fixes https://github.com/Spotifyd/spotifyd/issues/1295
> Bump time from 0.3.28 to 0.3.36

- src/alsa_mixer.rs
> clippy: use u16::MAX instead of max_value()

- docs/src/SUMMARY.md
- docs/src/installation/cross-compile-using-docker.md
Added a guide for cross compiling using docker for e.g. building arm64 as described in #1053
> Guide for cross compiling using docker

- CHANGELOG.md
- src/alsa_mixer.rs
fixes #1222
I hope, this fixes the issues mentioned with `alsa` and `alsa_linear`. Please note that one of them will behave weirdly on your system depending on, whether your alsa control is linear or not. (At least that is what I assume based on my experience...) However, they should both be able to reach 0% and not be reset when hitting play.
Any testing is appreciated. (maybe @Arbee4ever?)
> fix alsa mixer calculations

- src/utils.rs
This enables build in Termux on android
As a "proof" I'm providing a screenshot from the phone that it actually builds (with some features restricted) and it runs.
Bulit with:
```
cargo build --release --no-default-features --features pulseaudio_backend
```
and run with 
```
DISPLAY=0 ./target/release/spotifyd --no-daemon
```
> Enable build on android

- docs/src/config/File.md
- src/config.rs
`spotifyd` was lacking new device types (such as `automobile`, `gameconsole` etc.) introduced some time ago in `librespot`.
> Add new device types

- .github/workflows/cd.yml
- CHANGELOG.md
- Cargo.toml
- Cross.toml
Fixes #1334.
This fixes the selection of the `bindgen` feature, such that on most platforms, it should automatically choose the correct behaviour.
> chore: use resolver v2 for correct bindgen feature

- .github/workflows/cd.yml
This fixes the cd issue by resetting the cross cache and working around a `gcc-9` issue.
Fixes #1341 (again).
> cd: fix linux build

- Cargo.toml
The auto detection works fine and depends on everything that should be depended on afaict. Actual pulseaudio should not be depended on directly, only `libpulse0` (auto-detected) which is provided by both pulseaudio and pipewire.
Fixes #1346
> Remove extraneous deps for .deb package
